import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1788749828595 implements MigrationInterface {
    name = 'InitialSchema1788749828595'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "academic_years" ("id" SERIAL NOT NULL, "name" character varying(20) NOT NULL, "startYear" integer NOT NULL, "endYear" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_645d0f115fa85aaecffdc11cbaa" UNIQUE ("name"), CONSTRAINT "PK_2021b90bfbfa6c9da7df34ca1cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "faculties" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "code" character varying(20) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_39747c4153c669f1db683e8f231" UNIQUE ("name"), CONSTRAINT "UQ_f1b2cd43a96c6fb75c8ad44de88" UNIQUE ("code"), CONSTRAINT "PK_fd83e4a09c7182ccf7bdb3770b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "levels" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(20) NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_172e8f034ced78845089cca978d" UNIQUE ("name"), CONSTRAINT "PK_05f8dd8f715793c64d49e3f1901" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assessments" ("id" SERIAL NOT NULL, "course_id" integer NOT NULL, "name" character varying(150) NOT NULL, "type" character varying(30) NOT NULL, "maximumScore" numeric(5,2) NOT NULL, "weight" numeric(5,2) NOT NULL, "academicYear" character varying(20), "semester" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3442bd80a00e9111cefca57f6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "curricula" ("id" SERIAL NOT NULL, "program_id" integer NOT NULL, "level_id" integer NOT NULL, "academicYear" character varying(20) NOT NULL, "semester" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7c5dd2066e2bbf3b6ad0a71c567" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "curriculum_courses" ("id" SERIAL NOT NULL, "curriculum_id" integer NOT NULL, "course_id" integer NOT NULL, "isRequired" boolean NOT NULL DEFAULT true, "prerequisite_course_id" integer, CONSTRAINT "UQ_ba8e87f94d293bbf92f5bf2a4ca" UNIQUE ("curriculum_id", "course_id"), CONSTRAINT "PK_c1da7e5e440e1985553b1038dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "courses" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "code" character varying(20) NOT NULL, "description" text, "credits" integer NOT NULL, "department_id" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_86b3589486bac01d2903e22471c" UNIQUE ("code"), CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "enrollments" ("id" SERIAL NOT NULL, "student_id" integer NOT NULL, "course_id" integer NOT NULL, "academicYear" character varying(20) NOT NULL, "semester" integer NOT NULL, "enrollmentStatus" character varying NOT NULL DEFAULT 'enrolled', "attemptNumber" integer NOT NULL DEFAULT '1', "parent_enrollment_id" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e718a4bbc6163f8250ea5f8bc70" UNIQUE ("student_id", "course_id", "academicYear", "semester"), CONSTRAINT "PK_7c0f752f9fb68bf6ed7367ab00f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "students" ("id" SERIAL NOT NULL, "studentId" character varying(20) NOT NULL, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "dateOfBirth" date NOT NULL, "gender" character varying(20) NOT NULL, "profilePhoto" character varying(255), "nationality" character varying(100), "address" character varying(255), "phone" character varying(30), "email" character varying(150), "institutionalEmail" character varying(150) NOT NULL, "emergencyContactName" character varying(100), "emergencyContactRelationship" character varying(100), "emergencyContactPhone" character varying(30), "program_id" integer NOT NULL, "level_id" integer NOT NULL, "cohort_id" integer NOT NULL, "academicStatus" character varying NOT NULL DEFAULT 'active', "enrollmentDate" date NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9d9f010d4d6a6eea8b4779638c4" UNIQUE ("studentId"), CONSTRAINT "UQ_63d461652424ad8f2a4e6e32c89" UNIQUE ("institutionalEmail"), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cohorts" ("id" SERIAL NOT NULL, "program_id" integer NOT NULL, "startYear" integer NOT NULL, "endYear" integer NOT NULL, "code" character varying(10) NOT NULL, "maxStudentNumber" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e7b902a1c43653168889aa47fc1" UNIQUE ("code"), CONSTRAINT "PK_fd38f76b135e907b834fda1e752" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "programs" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "code" character varying(20) NOT NULL, "department_id" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d43c664bcaafc0e8a06dfd34e05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "code" character varying(20) NOT NULL, "faculty_id" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "description" character varying(255), CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" SERIAL NOT NULL, "student_id" integer NOT NULL, "course_id" integer NOT NULL, "date" date NOT NULL, "status" character varying(10) NOT NULL, "recorded_by" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c85d0f8fd04fe0ba89d3f211050" UNIQUE ("student_id", "course_id", "date"), CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "user_id" integer, "action" character varying(100) NOT NULL, "entity" character varying(100), "entity_id" integer, "details" text, "ipAddress" character varying, "timestamp" TIMESTAMP NOT NULL, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" SERIAL NOT NULL, "student_id" integer NOT NULL, "documentType" character varying(50) NOT NULL, "documentNumber" character varying(100) NOT NULL, "filePath" character varying(255), "generated_by" integer, "generatedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_31a376e7fc1150ddda491b4a0bd" UNIQUE ("documentNumber"), CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_fees" ("id" SERIAL NOT NULL, "student_id" integer NOT NULL, "feeType" character varying(30) NOT NULL, "description" character varying(150), "amount" numeric(12,2) NOT NULL, "academicYear" character varying(20) NOT NULL, "semester" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_285434ca1c7c8b2f79ea190bcac" UNIQUE ("student_id", "feeType", "academicYear", "semester"), CONSTRAINT "PK_a2cec5273eddb36c724e226cf13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "receipts" ("id" SERIAL NOT NULL, "payment_id" integer NOT NULL, "receiptNumber" character varying(50) NOT NULL, "generatedAt" TIMESTAMP NOT NULL, "generated_by" integer, "filePath" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ae91d6f7ca67ed5bf73177430d7" UNIQUE ("receiptNumber"), CONSTRAINT "REL_d2cfb7a62d629121d47a89ab98" UNIQUE ("payment_id"), CONSTRAINT "PK_5e8182d7c29e023da6e1ff33bfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" SERIAL NOT NULL, "student_id" integer NOT NULL, "fee_id" integer NOT NULL, "amount" numeric(12,2) NOT NULL, "paymentDate" date NOT NULL, "paymentMethod" character varying(30) NOT NULL, "paymentReference" character varying(100) NOT NULL, "recorded_by" integer, "status" character varying(20) NOT NULL DEFAULT 'active', "reversalNote" text, "reversedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_609e73477743140ae29ae6de486" UNIQUE ("paymentReference"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grades" ("id" SERIAL NOT NULL, "student_id" integer NOT NULL, "assessment_id" integer NOT NULL, "score" numeric(5,2) NOT NULL, "grade" character varying(5), "status" character varying(20) NOT NULL DEFAULT 'draft', "entered_by" integer, "validated_by" integer, "validatedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_555278255c7e92340eb5327447a" UNIQUE ("student_id", "assessment_id"), CONSTRAINT "PK_4740fb6f5df2505a48649f1687b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grade_history" ("id" SERIAL NOT NULL, "grade_id" integer NOT NULL, "previousScore" numeric(5,2) NOT NULL, "newScore" numeric(5,2) NOT NULL, "previousGrade" character varying(5), "newGrade" character varying(5), "action" character varying(20) NOT NULL, "changed_by" integer, "changedAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_e40a1b4d7c0c09958c4094565f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "student_id" integer, "staff_id" integer, "type" character varying(30) NOT NULL, "title" character varying(150) NOT NULL, "message" text NOT NULL, "level" character varying NOT NULL DEFAULT 'info', "read" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL, "relatedEntity" character varying, "related_entity_id" integer, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "announcements" ("id" SERIAL NOT NULL, "title" character varying(200) NOT NULL, "body" text NOT NULL, "targetType" character varying(30) NOT NULL, "target_id" integer, "created_by" integer, "publishedAt" TIMESTAMP NOT NULL, "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b3ad760876ff2e19d58e05dc8b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staff" ("id" SERIAL NOT NULL, "staffId" character varying(20) NOT NULL, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "email" character varying(150) NOT NULL, "phone" character varying(30), "department_id" integer NOT NULL, "position" character varying(100) NOT NULL, "qualifications" text, "status" character varying NOT NULL DEFAULT 'active', "isLecturer" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a455629d6ffbd1f2953f453f3f9" UNIQUE ("staffId"), CONSTRAINT "UQ_902985a964245652d5e3a0f5f6a" UNIQUE ("email"), CONSTRAINT "PK_e4ee98bb552756c180aec1e854a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course_assignments" ("id" SERIAL NOT NULL, "staff_id" integer NOT NULL, "course_id" integer NOT NULL, "academicYear" character varying(20) NOT NULL, "semester" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_44622adcc97308a4c1584cacb88" UNIQUE ("staff_id", "course_id", "academicYear", "semester"), CONSTRAINT "PK_601138f857c63944c5972108dff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "timetable_entries" ("id" SERIAL NOT NULL, "course_id" integer NOT NULL, "classType" character varying(20) NOT NULL, "dayOfWeek" integer NOT NULL, "startTime" character varying(10) NOT NULL, "endTime" character varying(10) NOT NULL, "location" character varying(100), "lecturer_id" integer, "academicYear" character varying(20) NOT NULL, "semester" integer NOT NULL, "startDate" date NOT NULL, "endDate" date, "status" character varying NOT NULL DEFAULT 'scheduled', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_11b6792dfdc5dd6849abed870d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "username" character varying(150) NOT NULL, "passwordHash" character varying(255) NOT NULL, "role_id" integer NOT NULL, "linkedStudentId" integer, "linkedStaffId" integer, "status" character varying NOT NULL DEFAULT 'active', "mustChangePassword" boolean NOT NULL DEFAULT true, "failedLoginAttempts" integer NOT NULL DEFAULT '0', "lockedUntil" TIMESTAMP, "lastLoginAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "linked_student_id" integer, "linked_staff_id" integer, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "REL_1b073d9d312e634aed19de582d" UNIQUE ("linked_student_id"), CONSTRAINT "REL_37a7a630db0851c1261cccca9b" UNIQUE ("linked_staff_id"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions"  ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions"  ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_2d76c87300726d247589833f63f" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curricula" ADD CONSTRAINT "FK_6186c47ace232293268fb7ba2c3" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curricula" ADD CONSTRAINT "FK_67cf46d9fea83d5fa491d1f442d" FOREIGN KEY ("level_id") REFERENCES "levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_courses" ADD CONSTRAINT "FK_e3fde6bf042b045b9d0ed3707e5" FOREIGN KEY ("curriculum_id") REFERENCES "curricula"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_courses" ADD CONSTRAINT "FK_1cb1fa73e952255bd8069f78892" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_b0a306ca76ad64906bf5082775f" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_307813fe255896d6ebf3e6cd55c" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_b79d0bf01779fdf9cfb6b092af3" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_2a7ac955ea573f8be71d736cef8" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_ebc3adae3c7b211f927b6403bc5" FOREIGN KEY ("level_id") REFERENCES "levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_5b672e37079ea9049dbe2ff3106" FOREIGN KEY ("cohort_id") REFERENCES "cohorts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cohorts" ADD CONSTRAINT "FK_d8e49c656a43855ec1b0f1ff1b5" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "FK_95acfc8225a0719c2cfe7dcdac0" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_db9cbab5eb895126fc1689dc2ad" FOREIGN KEY ("faculty_id") REFERENCES "faculties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_6200532f3ef99f639a27bdcae7f" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_0ce01e85e94ccecea83365bb36f" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_add06d9cca9b67e7392a060b6c7" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_fees" ADD CONSTRAINT "FK_9e8969b8c743de99403b16b592c" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD CONSTRAINT "FK_d2cfb7a62d629121d47a89ab989" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_9fd5d6ef620b0140a67ff2d95c4" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_02a66e9bd67a2d3bd8e051afa69" FOREIGN KEY ("fee_id") REFERENCES "student_fees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grades" ADD CONSTRAINT "FK_9acca493883cee3b9e8f9e01cd1" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grades" ADD CONSTRAINT "FK_01a840e819595a73786b234f4ee" FOREIGN KEY ("assessment_id") REFERENCES "assessments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grade_history" ADD CONSTRAINT "FK_6d222446a4b2c11c1de7962f03e" FOREIGN KEY ("grade_id") REFERENCES "grades"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_ce06bae9cc27770d5ee158d8ceb" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_51b371508b14db31bee80fded0a" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_assignments" ADD CONSTRAINT "FK_ee99246f2f7ef1057f2a02e4c91" FOREIGN KEY ("staff_id") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_assignments" ADD CONSTRAINT "FK_ced68e02ed45eb8c72cc1b42348" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetable_entries" ADD CONSTRAINT "FK_b98681cdbaf58e4741d47b479c4" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetable_entries" ADD CONSTRAINT "FK_654d9c307d5834d4a0745129cda" FOREIGN KEY ("lecturer_id") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_1b073d9d312e634aed19de582d3" FOREIGN KEY ("linked_student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_37a7a630db0851c1261cccca9bb" FOREIGN KEY ("linked_staff_id") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_37a7a630db0851c1261cccca9bb"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_1b073d9d312e634aed19de582d3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "timetable_entries" DROP CONSTRAINT "FK_654d9c307d5834d4a0745129cda"`);
        await queryRunner.query(`ALTER TABLE "timetable_entries" DROP CONSTRAINT "FK_b98681cdbaf58e4741d47b479c4"`);
        await queryRunner.query(`ALTER TABLE "course_assignments" DROP CONSTRAINT "FK_ced68e02ed45eb8c72cc1b42348"`);
        await queryRunner.query(`ALTER TABLE "course_assignments" DROP CONSTRAINT "FK_ee99246f2f7ef1057f2a02e4c91"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_51b371508b14db31bee80fded0a"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_ce06bae9cc27770d5ee158d8ceb"`);
        await queryRunner.query(`ALTER TABLE "grade_history" DROP CONSTRAINT "FK_6d222446a4b2c11c1de7962f03e"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP CONSTRAINT "FK_01a840e819595a73786b234f4ee"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP CONSTRAINT "FK_9acca493883cee3b9e8f9e01cd1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_02a66e9bd67a2d3bd8e051afa69"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_9fd5d6ef620b0140a67ff2d95c4"`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP CONSTRAINT "FK_d2cfb7a62d629121d47a89ab989"`);
        await queryRunner.query(`ALTER TABLE "student_fees" DROP CONSTRAINT "FK_9e8969b8c743de99403b16b592c"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_add06d9cca9b67e7392a060b6c7"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_0ce01e85e94ccecea83365bb36f"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_6200532f3ef99f639a27bdcae7f"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_db9cbab5eb895126fc1689dc2ad"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "FK_95acfc8225a0719c2cfe7dcdac0"`);
        await queryRunner.query(`ALTER TABLE "cohorts" DROP CONSTRAINT "FK_d8e49c656a43855ec1b0f1ff1b5"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_5b672e37079ea9049dbe2ff3106"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_ebc3adae3c7b211f927b6403bc5"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_2a7ac955ea573f8be71d736cef8"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_b79d0bf01779fdf9cfb6b092af3"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_307813fe255896d6ebf3e6cd55c"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_b0a306ca76ad64906bf5082775f"`);
        await queryRunner.query(`ALTER TABLE "curriculum_courses" DROP CONSTRAINT "FK_1cb1fa73e952255bd8069f78892"`);
        await queryRunner.query(`ALTER TABLE "curriculum_courses" DROP CONSTRAINT "FK_e3fde6bf042b045b9d0ed3707e5"`);
        await queryRunner.query(`ALTER TABLE "curricula" DROP CONSTRAINT "FK_67cf46d9fea83d5fa491d1f442d"`);
        await queryRunner.query(`ALTER TABLE "curricula" DROP CONSTRAINT "FK_6186c47ace232293268fb7ba2c3"`);
        await queryRunner.query(`ALTER TABLE "assessments" DROP CONSTRAINT "FK_2d76c87300726d247589833f63f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "timetable_entries"`);
        await queryRunner.query(`DROP TABLE "course_assignments"`);
        await queryRunner.query(`DROP TABLE "staff"`);
        await queryRunner.query(`DROP TABLE "announcements"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "grade_history"`);
        await queryRunner.query(`DROP TABLE "grades"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TABLE "receipts"`);
        await queryRunner.query(`DROP TABLE "student_fees"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "programs"`);
        await queryRunner.query(`DROP TABLE "cohorts"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TABLE "enrollments"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`DROP TABLE "curriculum_courses"`);
        await queryRunner.query(`DROP TABLE "curricula"`);
        await queryRunner.query(`DROP TABLE "assessments"`);
        await queryRunner.query(`DROP TABLE "levels"`);
        await queryRunner.query(`DROP TABLE "faculties"`);
        await queryRunner.query(`DROP TABLE "academic_years"`);
    }

}
