export const PermissionsCatalog = {
  STUDENT_VIEW: 'student.view',
  STUDENT_CREATE: 'student.create',
  STUDENT_UPDATE: 'student.update',
  STUDENT_DELETE: 'student.delete',
  STAFF_VIEW: 'staff.view',
  STAFF_CREATE: 'staff.create',
  STAFF_UPDATE: 'staff.update',
  STAFF_DELETE: 'staff.delete',
  ACADEMIC_VIEW: 'academic.view',
  ACADEMIC_CREATE: 'academic.create',
  ACADEMIC_UPDATE: 'academic.update',
  ACADEMIC_DELETE: 'academic.delete',
  COURSE_VIEW: 'course.view',
  COURSE_CREATE: 'course.create',
  COURSE_UPDATE: 'course.update',
  COURSE_DELETE: 'course.delete',
  CURRICULUM_VIEW: 'curriculum.view',
  CURRICULUM_CREATE: 'curriculum.create',
  CURRICULUM_UPDATE: 'curriculum.update',
  CURRICULUM_DELETE: 'curriculum.delete',
  ENROLLMENT_VIEW: 'enrollment.view',
  ENROLLMENT_MANAGE: 'enrollment.manage',
  ASSIGNMENT_MANAGE: 'assignment.manage',
  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_MANAGE: 'attendance.manage',
  ASSESSMENT_VIEW: 'assessment.view',
  ASSESSMENT_MANAGE: 'assessment.manage',
  GRADE_ENTER: 'grade.enter',
  GRADE_SUBMIT: 'grade.submit',
  GRADE_VALIDATE: 'grade.validate',
  GRADE_CORRECT: 'grade.correct',
  GRADE_VIEW: 'grade.view',
  TIMETABLE_VIEW: 'timetable.view',
  TIMETABLE_MANAGE: 'timetable.manage',
  FINANCE_VIEW: 'finance.view',
  FEES_MANAGE: 'fees.manage',
  PAYMENT_RECORD: 'payment.record',
  PAYMENT_REVERSE: 'payment.reverse',
  RECEIPT_GENERATE: 'receipt.generate',
  DOCUMENT_VIEW: 'document.view',
  DOCUMENT_GENERATE: 'document.generate',
  NOTIFICATION_MANAGE: 'notification.manage',
  ANNOUNCEMENT_MANAGE: 'announcement.manage',
  ANNOUNCEMENT_VIEW: 'announcement.view',
  USER_CREATE: 'user.create',
  USER_UPDATE: 'user.update',
  USER_VIEW: 'user.view',
  ROLE_MANAGE: 'role.manage',
  PERMISSION_MANAGE: 'permission.manage',
  AUDIT_VIEW: 'audit.view',
  REPORT_VIEW: 'report.view',
  SYSTEM_CONFIG: 'system.config',
  REFUND_VIEW: 'refund.view',
  REFUND_REQUEST: 'refund.request',
  REFUND_MANAGE: 'refund.manage',
  EVALUATION_VIEW: 'evaluation.view',
  EVALUATION_SUBMIT: 'evaluation.submit',
  EVALUATION_CONFIG: 'evaluation.config',
  EVALUATION_RESULT: 'evaluation.result',
  EVALUATION_ANALYZE: 'evaluation.analyze',
} as const;

export type PermissionName = (typeof PermissionsCatalog)[keyof typeof PermissionsCatalog];

export const ALL_PERMISSIONS: PermissionName[] = Object.values(PermissionsCatalog);